codecov: true
language: julia
julia:
  - 1.5.2
  - nightly

script:
  - julia -e 'using Pkg; Pkg.build(; verbose=true); Pkg.test(coverage=true)';

after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
